### ISSUE TITLE
If user is not in tracing group, there should be a warning.

### ISSUE THREAD

**Issue by TheMatthew** [tahini/lttng-utils#1]
The warning should tell the user : 

sudo usermod -a -G tracing <user>

**Comment by tahini** [comment]
If kernel tracing is requested and the user is not in the tracing group, what would be most appropriate?

1- Print a warning and exit?
2- Print the warning and try running the trace with sudo lttng?
3- Print the warning and exit and offer an additional argument option to run lttng as sudo if required?

**Comment by TheMatthew** [comment]
I would put the warning and exit.

Say something like: 

either sudo or add your user to tracing. warn also that sudo will make your traces owned by root.

My 2c
