### ISSUE TITLE
Critical TypeError 

### ISSUE THREAD

**Issue by qfournier** [tahini/lttng-utils#6]
```
sudo lttng-record-trace 

Traceback (most recent call last):
  File "/usr/local/bin/lttng-record-trace", line 60, in <module>
    lttngProfiles = profile.Profile()
  File "/usr/local/lib/python3.6/dist-packages/lttngutils/profile.py", line 35, in __init__
    os.path.join(os.getenv("PWD"), "profiles/")]
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This is due to `os.getenv("PWD")` line 33 of [profile.py](https://github.com/tahini/lttng-utils/blob/master/lttngutils/profile.py) returning None (maybe related to [https://bugs.python.org/issue30167](https://bugs.python.org/issue30167))

It seems that it can be solved by replacing `os.getenv("PWD")` by `os.getcwd()` line 33 of [profile.py](https://github.com/tahini/lttng-utils/blob/master/lttngutils/profile.py) and line 63 of [lttng-record-trace](https://github.com/tahini/lttng-utils/blob/master/lttng-record-trace).

The environnement:
- Ubuntu 18.04.1
- Python 3.6.7
- see [requirements_global.txt](https://github.com/tahini/lttng-utils/files/2741676/requirements_global.txt) and [requirements_venv.txt](https://github.com/tahini/lttng-utils/files/2741677/requirements_venv.txt)  for python packages

**Comment by tahini** [comment]
Thanks for this bug and the way to fix it! Can you try the linked commit above and let me know if it works fine with your version of python?

**Comment by qfournier** [comment]
It works!
